export const mails = [
  {
    id: 1,
    name: "Quire",
    subject: "Morbi vel lectus in quam fringilla rhoncus.",
    text: "Integer ac leo. Pellentesque ultrices mattis odio.",
    starred: false,
    isRead: true,
    date: "2023-03-23T10:19:21Z",
    category: "primary",
    label: "work",
  },
  {
    id: 2,
    name: "Trilith",
    subject: "In hac habitasse platea dictumst.",
    text: "Aenean auctor gravida sem.",
    starred: true,
    isRead: false,
    date: "2023-07-01T19:17:57Z",
    category: "primary",
    label: "work",
  },
  {
    id: 3,
    name: "Rhyloo",
    subject: "Etiam justo.",
    text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.",
    starred: true,
    isRead: false,
    date: "2023-12-26T11:06:47Z",
    category: "primary",
    label: "work",
  },
  {
    id: 4,
    name: "Katz",
    subject: "Donec semper sapien a libero.",
    text: "Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.",
    starred: true,
    isRead: true,
    date: "2023-09-29T15:01:49Z",
    category: "primary",
    label: "company",
  },
  {
    id: 5,
    name: "Quinu",
    subject: "Nulla tempus.",
    text: "Maecenas rhoncus aliquam lacus.",
    starred: false,
    isRead: true,
    date: "2023-10-31T15:16:08Z",
    category: "social",
    label: "work",
  },
  {
    id: 6,
    name: "Gabspot",
    subject: "Cras pellentesque volutpat dui.",
    text: "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.",
    starred: true,
    isRead: true,
    date: "2023-02-18T03:38:23Z",
    category: "social",
    label: "private",
  },
  {
    id: 7,
    name: "Jabbercube",
    subject: "Morbi non lectus.",
    text: "Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
    starred: true,
    isRead: true,
    date: "2023-02-13T06:28:07Z",
    category: "social",
    label: "private",
  },
  {
    id: 8,
    name: "Kwinu",
    subject: "Praesent lectus.",
    text: "Aliquam erat volutpat. In congue.",
    starred: true,
    isRead: true,
    date: "2023-02-25T23:48:12Z",
    category: "social",
    label: "group",
  },
  {
    id: 9,
    name: "Aimbu",
    subject: "Sed accumsan felis.",
    text: "Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.",
    starred: false,
    isRead: true,
    date: "2023-05-03T12:41:09Z",
    category: "social",
    label: "private",
  },
  {
    id: 10,
    name: "Tekfly",
    subject:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    text: "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.",
    starred: true,
    isRead: true,
    date: "2023-11-25T04:52:27Z",
    category: "social",
    label: "work",
  },
  {
    id: 11,
    name: "Realcube",
    subject: "Integer a nibh.",
    text: "Morbi a ipsum.",
    starred: false,
    isRead: true,
    date: "2023-04-13T20:24:08Z",
    category: "promotions",
    label: "private",
  },
  {
    id: 12,
    name: "Zoombeat",
    subject: "Nam tristique tortor eu pede.",
    text: "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.",
    starred: false,
    isRead: true,
    date: "2023-06-29T05:24:17Z",
    category: "promotions",
    label: "work",
  },
  {
    id: 13,
    name: "Edgeclub",
    subject: "Nullam varius.",
    text: "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
    starred: true,
    isRead: false,
    date: "2023-07-11T10:20:19Z",
    category: "promotions",
    label: "company",
  },
  {
    id: 14,
    name: "Twimbo",
    subject:
      "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.",
    text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.",
    starred: false,
    isRead: true,
    date: "2024-02-03T15:40:05Z",
    category: "promotions",
    label: "private",
  },
  {
    id: 15,
    name: "Skimia",
    subject: "In quis justo.",
    text: "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    starred: false,
    isRead: true,
    date: "2023-03-01T08:21:53Z",
    category: "promotions",
    label: "group",
  },
  {
    id: 16,
    name: "Dazzlesphere",
    subject: "Integer a nibh.",
    text: "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.",
    starred: true,
    isRead: true,
    date: "2023-07-19T21:44:28Z",
    category: "promotions",
    label: "work",
  },
  {
    id: 17,
    name: "DabZ",
    subject: "In hac habitasse platea dictumst.",
    text: "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.",
    starred: true,
    isRead: false,
    date: "2023-10-27T08:15:19Z",
    category: "promotions",
    label: "work",
  },
  {
    id: 18,
    name: "Midel",
    subject:
      "Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    text: "Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.",
    starred: true,
    isRead: false,
    date: "2023-03-22T03:10:13Z",
    category: "promotions",
    label: "work",
  },
  {
    id: 19,
    name: "Leenti",
    subject: "Cras non velit nec nisi vulputate nonummy.",
    text: "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    starred: false,
    isRead: false,
    date: "2023-08-26T13:27:02Z",
    category: "promotions",
    label: "company",
  },
  {
    id: 20,
    name: "Twinte",
    subject: "Etiam vel augue.",
    text: "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.",
    starred: false,
    isRead: true,
    date: "2023-04-27T16:41:36Z",
    category: "promotions",
    label: "company",
  },
  {
    id: 21,
    name: "Zoomcast",
    subject:
      "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    text: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.",
    starred: false,
    isRead: false,
    date: "2023-09-30T23:35:45Z",
    category: "primary",
    label: "company",
  },
  {
    id: 22,
    name: "Kwideo",
    subject: "Maecenas ut massa quis augue luctus tincidunt.",
    text: "Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    starred: false,
    isRead: false,
    date: "2023-07-26T11:39:09Z",
    category: "primary",
    label: "private",
  },
  {
    id: 23,
    name: "Skibox",
    subject: "Aenean auctor gravida sem.",
    text: "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
    starred: true,
    isRead: false,
    date: "2023-12-20T14:25:05Z",
    category: "primary",
    label: "company",
  },
  {
    id: 24,
    name: "Roodel",
    subject: "Morbi non lectus.",
    text: "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.",
    starred: true,
    isRead: true,
    date: "2023-02-19T21:53:47Z",
    category: "primary",
    label: "private",
  },
  {
    id: 25,
    name: "Photobug",
    subject:
      "Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    text: "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    starred: true,
    isRead: false,
    date: "2023-07-18T11:15:31Z",
    category: "primary",
    label: "company",
  },
  {
    id: 26,
    name: "Topiczoom",
    subject: "Nullam porttitor lacus at turpis.",
    text: "Nullam porttitor lacus at turpis.",
    starred: false,
    isRead: false,
    date: "2023-04-18T02:19:13Z",
    category: "primary",
    label: "company",
  },
  {
    id: 27,
    name: "Trudeo",
    subject: "Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    text: "Mauris lacinia sapien quis libero.",
    starred: true,
    isRead: true,
    date: "2023-05-30T03:49:43Z",
    category: "primary",
    label: "private",
  },
  {
    id: 28,
    name: "Meemm",
    subject: "Nullam varius.",
    text: "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.",
    starred: true,
    isRead: true,
    date: "2023-12-17T21:48:43Z",
    category: "primary",
    label: "group",
  },
  {
    id: 29,
    name: "Kare",
    subject: "Duis mattis egestas metus.",
    text: "Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    starred: false,
    isRead: true,
    date: "2023-11-27T00:45:28Z",
    category: "primary",
    label: "company",
  },
  {
    id: 30,
    name: "Gabtune",
    subject: "Aenean sit amet justo.",
    text: "Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    starred: true,
    isRead: false,
    date: "2023-04-05T04:00:15Z",
    category: "primary",
    label: "company",
  },
];
