import { faker } from "@faker-js/faker";

export const data = [
  {
    id: "m5gr84i9",
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    amount: 316,
    status: "success",
    email: "ken99@yahoo.com",
  },
  {
    id: "3u1reuv4",
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    amount: 242,
    status: "success",
    email: "Abe45@gmail.com",
  },
  {
    id: "derv1ws0",
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    amount: 837,
    status: "processing",
    email: "Monserrat44@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "5kma53ae",
    amount: 874,
    status: "success",
    email: "Silas22@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "bhqecj4p",
    amount: 721,
    status: "failed",
    email: "carmella@hotmail.com",
  },
  {
    id: "m5gr84i10",
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    amount: 316,
    status: "success",
    email: "ken99@yahoo.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "3u1reuv4",
    amount: 242,
    status: "success",
    email: "Abe45@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "derv1ws0",
    amount: 837,
    status: "processing",
    email: "Monserrat44@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "5kma53ae",
    amount: 874,
    status: "success",
    email: "Silas22@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "bhqecj4p",
    amount: 721,
    status: "failed",
    email: "carmella@hotmail.com",
  },
  {
    id: "m5gr84i122",
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    amount: 316,
    status: "success",
    email: "ken99@yahoo.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "3u1reuv4222",
    amount: 242,
    status: "success",
    email: "Abe45@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "derv1ws0222",
    amount: 837,
    status: "processing",
    email: "Monserrat44@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "5kma53ae",
    amount: 874,
    status: "success",
    email: "Silas22@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "bhqecj4p",
    amount: 721,
    status: "failed",
    email: "carmella@hotmail.com",
  },
  {
    id: "m5gr84i922278",
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    amount: 316,
    status: "success",
    email: "ken99@yahoo.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "3u1reuv4123",
    amount: 242,
    status: "success",
    email: "Abe45@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "derv1ws0552",
    amount: 837,
    status: "processing",
    email: "Monserrat44@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "5kma53ae",
    amount: 874,
    status: "success",
    email: "Silas22@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "bhqecj4p",
    amount: 721,
    status: "failed",
    email: "carmella@hotmail.com",
  },
  {
    id: "m5gr84i98657",
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    amount: 316,
    status: "success",
    email: "ken99@yahoo.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "3u1reuv21054",
    amount: 242,
    status: "success",
    email: "Abe45@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "derv1ws0",
    amount: 837,
    status: "processing",
    email: "Monserrat44@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "5kma53ae656ty",
    amount: 874,
    status: "success",
    email: "Silas22@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "bhqecfdghfj4p",
    amount: 721,
    status: "failed",
    email: "carmella@hotmail.com",
  },
  {
    id: "m5gr8dfgjrf4i9",
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    amount: 316,
    status: "success",
    email: "ken99@yahoo.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "3u1reuv4jtyrs",
    amount: 242,
    status: "success",
    email: "Abe45@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "derv1wrtyrss0",
    amount: 837,
    status: "processing",
    email: "Monserrat44@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "5kma53eryerae",
    amount: 874,
    status: "success",
    email: "Silas22@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "bhersyqecj4p",
    amount: 721,
    status: "failed",
    email: "carmella@hotmail.com",
  },
  {
    id: "m5gr84ieryre9",
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    amount: 316,
    status: "success",
    email: "ken99@yahoo.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "3u1reuv4",
    amount: 242,
    status: "success",
    email: "Abe45@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "derv1wresyerys0",
    amount: 837,
    status: "processing",
    email: "Monserrat44@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "5kmaaserujr53ae",
    amount: 874,
    status: "success",
    email: "Silas22@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "bhqecj4p",
    amount: 721,
    status: "failed",
    email: "carmella@hotmail.com",
  },
  {
    id: "m5gr8ryrey4i9",
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    amount: 316,
    status: "success",
    email: "ken99@yahoo.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "3u1sryreyrreuv4",
    amount: 242,
    status: "success",
    email: "Abe45@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "derv1ryhrsws0",
    amount: 837,
    status: "processing",
    email: "Monserrat44@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "5kmaryrs53ae",
    amount: 874,
    status: "success",
    email: "Silas22@gmail.com",
  },
  {
    user: {
      name: "Lindsay Walton",
      avatar: faker.image.avatarLegacy(),
      title: "Front-end Developer",
      email: "lindsay.walton@example.com",
    },
    id: "bhqecjsrfj4p",
    amount: 721,
    status: "failed",
    email: "carmella@hotmail.com",
  },
];

