export const messages = [
  {
    id: 1,
    userId: 1,
    senderName: "Felcia Rower",
    avatar: "/images/avatar/avatar-2.jpg",
    time: "Mon Dec 10 2018 07:45:00 GMT+0000 (GMT)",
    messages: ["Hi"],
  },
  {
    id: 2,
    userId: 2,
    senderName: "Asif Khan",
    avatar: "/images/avatar/avatar-7.jpg",
    time: "Mon Dec 10 2018 07:45:00 GMT+0000 (GMT)",
    messages: ["Hi", "How are you?"],
  },
  {
    id: 3,
    userId: 1,
    senderName: "Felcia Rower",
    avatar: "/images/avatar/avatar-3.jpg",
    time: "Mon Dec 10 2018 07:45:00 GMT+0000 (GMT)",
    messages: ["Hi", "I'm fine?"],
  },
  {
    id: 4,
    userId: 3,
    senderName: "Felcia Rower",
    avatar: "/images/avatar/avatar-4.jpg",
    time: "Mon Dec 10 2018 07:45:00 GMT+0000 (GMT)",
    messages: ["Hi! Everyone!"],
  },
  {
    id: 5,
    userId: 5,
    senderName: "Felcia Rower",
    avatar: "/images/avatar/avatar-4.jpg",
    time: "Mon Dec 10 2018 07:45:00 GMT+0000 (GMT)",
    messages: ["How is the day going?"],
  },
  {
    id: 6,
    userId: 1,
    senderName: "Felcia Rower",
    avatar: "/images/avatar/avatar-7.jpg",
    time: "Mon Dec 10 2018 07:45:00 GMT+0000 (GMT)",
    messages: ["I'm good. and you?"],
  },
  {
    id: 7,
    userId: 5,
    senderName: "Felcia Rower",
    avatar: "/images/avatar/avatar-4.jpg",
    time: "Mon Dec 10 2018 07:45:00 GMT+0000 (GMT)",
    messages: ["How is the day going?"],
  },
  {
    id: 8,
    userId: 1,
    senderName: "Felcia Rower",
    avatar: "/images/avatar/avatar-7.jpg",
    time: "Mon Dec 10 2018 07:45:00 GMT+0000 (GMT)",
    messages: ["I'm good. and you?", "Which features do you like?"],
  },
  {
    id: 9,
    userId: 5,
    senderName: "Felcia Rower",
    avatar: "/images/avatar/avatar-7.jpg",
    time: "Mon Dec 10 2018 07:45:00 GMT+0000 (GMT)",
    messages: [
      "I'm good. and you?",
      "Which features do you like?",
      "Kindly send me a few demos.",
    ],
  },
  {
    id: 10,
    userId: 5,
    senderName: "Felcia Rower",
    avatar: "/images/avatar/avatar-4.jpg",
    time: "Mon Dec 10 2018 07:45:00 GMT+0000 (GMT)",
    messages: ["How is the day going?"],
  },
  {
    id: 11,
    userId: 1,
    senderName: "Felcia Rower",
    avatar: "/images/avatar/avatar-7.jpg",
    time: "Mon Dec 10 2018 07:45:00 GMT+0000 (GMT)",
    messages: ["I'm good. and you?", "Which features do you like?"],
  },
  {
    id: 12,
    userId: 5,
    senderName: "Felcia Rower",
    avatar: "/images/avatar/avatar-7.jpg",
    time: "Mon Dec 10 2018 07:45:00 GMT+0000 (GMT)",
    messages: [
      "I'm good. and you?",
      "Which features do you like?",
      "Kindly send me a few demos.",
    ],
  },
];
